# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UAVver0.1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 960))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 960))
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.TabWidget = QtWidgets.QTabWidget(MainWindow)
        self.TabWidget.setObjectName("TabWidget")
        self.MapTab = QtWidgets.QWidget()
        self.MapTab.setObjectName("MapTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.MapTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.maptab_layout = QtWidgets.QGridLayout()
        self.maptab_layout.setObjectName("maptab_layout")
        self.MapFrame = QtWidgets.QFrame(self.MapTab)
        self.MapFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MapFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MapFrame.setObjectName("MapFrame")
        self.maptab_layout.addWidget(self.MapFrame, 0, 0, 1, 3)
        self.enter_button = QtWidgets.QPushButton(self.MapTab)
        self.enter_button.setObjectName("enter_button")
        self.maptab_layout.addWidget(self.enter_button, 2, 2, 1, 1)
        self.input_label = QtWidgets.QLabel(self.MapTab)
        self.input_label.setObjectName("input_label")
        self.maptab_layout.addWidget(self.input_label, 2, 0, 1, 1)
        self.output_text = QtWidgets.QTextEdit(self.MapTab)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.maptab_layout.addWidget(self.output_text, 1, 1, 1, 1)
        self.output_label = QtWidgets.QLabel(self.MapTab)
        self.output_label.setObjectName("output_label")
        self.maptab_layout.addWidget(self.output_label, 1, 0, 1, 1)
        self.input_text = QtWidgets.QLineEdit(self.MapTab)
        self.input_text.setInputMask("")
        self.input_text.setText("")
        self.input_text.setObjectName("input_text")
        self.maptab_layout.addWidget(self.input_text, 2, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.MapTab)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.maptab_layout.addWidget(self.verticalScrollBar, 1, 2, 1, 1)
        self.maptab_layout.setRowStretch(0, 7)
        self.gridLayout_3.addLayout(self.maptab_layout, 1, 0, 1, 1)
        self.TabWidget.addTab(self.MapTab, "")
        self.UAVListTab = QtWidgets.QWidget()
        self.UAVListTab.setObjectName("UAVListTab")
        self.listWidget = QtWidgets.QListWidget(self.UAVListTab)
        self.listWidget.setGeometry(QtCore.QRect(30, 80, 256, 311))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton = QtWidgets.QPushButton(self.UAVListTab)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.TabWidget.addTab(self.UAVListTab, "")
        self.MediaTab = QtWidgets.QWidget()
        self.MediaTab.setObjectName("MediaTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.MediaTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1231, 891))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.MediaTabLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.MediaTabLayout.setContentsMargins(0, 0, 0, 0)
        self.MediaTabLayout.setObjectName("MediaTabLayout")
        self.MediaFrame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.MediaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MediaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MediaFrame.setObjectName("MediaFrame")
        self.MediaTabLayout.addWidget(self.MediaFrame, 0, 0, 1, 1)
        self.TabWidget.addTab(self.MediaTab, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.label = QtWidgets.QLabel(self.SettingsTab)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.SettingsTab)
        self.toolButton.setGeometry(QtCore.QRect(420, 30, 31, 21))
        self.toolButton.setObjectName("toolButton")
        self.lineEdit = QtWidgets.QLineEdit(self.SettingsTab)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 261, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.TabWidget.addTab(self.SettingsTab, "")
        self.gridLayout.addWidget(self.TabWidget, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "无人机集群管理系统"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
        self.input_label.setText(_translate("MainWindow", "input"))
        self.output_label.setText(_translate("MainWindow", "output"))
        self.input_text.setPlaceholderText(_translate("MainWindow", ">>>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.MapTab), _translate("MainWindow", "地图"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "添加无人机"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.UAVListTab), _translate("MainWindow", "无人机"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.MediaTab), _translate("MainWindow", "媒体"))
        self.label.setText(_translate("MainWindow", "媒体存储目录："))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.SettingsTab), _translate("MainWindow", "设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

